<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/9
 * Time: 16:50
 */
class HomeStone extends Block
{
    protected static $concept;
    protected static $id;
    protected static $die;
    protected static $length;
    protected static $width;

    protected static $hp;
    protected static $life;
    protected static $side;
    protected static $is_no_enemy;

    protected $protect_buff; // 加固buff

    function destroy($update = true)
    {
        $tanks = $this->getMap()->getPlayerTanks();
        /** @var PlayerTank $tank */
        foreach ($tanks as $tank)
        {
            $tank->savePayMineNum();
            $tank->savePayFollowBulletNum();
        }
        parent::destroy($update); // TODO: Change the autogenerated stub
        $this->getMap()->getGame()->flushUpdateInfo();
        $this->getMap()->getGame()->destroy();
    }

    /**
     * @return mixed
     */
    public function getProtectBuff()
    {
        return $this->protect_buff;
    }

    /**
     * @param mixed $protect_buff
     */
    public function setProtectBuff($protect_buff)
    {
        $this->protect_buff = $protect_buff;
    }
}


