<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/8
 * Time: 15:54
 */
class WaterFace extends Terrain
{
    protected static $id;
    protected static $length;
    protected static $width;
    protected static $concept;

    function effect($tank)
    {
        parent::effect($tank); // TODO: Change the autogenerated stub
        if (empty($tank->getLifeBuff()) || !is_a($tank->getLifeBuff(),"SheepBuff")){
            $tank->setCanMove(0);
        }
        return null;
    }
}