<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/24
 * Time: 11:32
 */
class MoveUpBuff extends Buff
{
    protected static $concept;
    protected static $id;
    protected static $die;
    protected static $length;
    protected static $width;

    protected static $buff_type;

    protected static $move_up;

    /**
     * @return mixed
     */
    public function getMoveUp()
    {
        return $this->move_up??static::$move_up;
    }

    /**
     * @param mixed $move_up
     */
    public function setMoveUp($move_up)
    {
        $this->move_up = $move_up;
    }

    public static function getMoveUpStatic(){
        return static::$move_up;
    }

    function active()
    {
        parent::active(); // TODO: Change the autogenerated stub
        $this->getTankGot()->moveUp($this->getMoveUp());
    }
}