<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/9
 * Time: 18:40
 */
class NoEnemyBuff extends Buff
{
    protected static $concept;
    protected static $id;
    protected static $die;
    protected static $length;
    protected static $width;

    protected static $buff_type;
    protected static $continue_time;


    public function active()
    {
        $this->getTankGot()->setNoEnemy(true);
        $this->loop();
        return $this;
    }

    public function loop()
    {
        $timer_id = \Workerman\Lib\Timer::add(1, function () {
            if ($this->isOverTime()) {
                $this->destroy();
            }
        });
        return $this->setTimerId($timer_id);
    }

    public function isOverTime()
    {
        return getMillisecond() > $this->getGetTime() + $this->getContinueTime();
    }

    public function invalid()
    {
        parent::invalid(); // TODO: Change the autogenerated stub
        return $this->getTankGot()->setNoEnemy(false);
    }

    /**
     * @return mixed
     */
    public function getContinueTime()
    {
        return $this->continue_time ?? static::$continue_time;
    }
}