<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/24
 * Time: 11:54
 */
class ShootIntervalDownBuff extends Buff
{
    protected static $concept;
    protected static $id;
    protected static $die;
    protected static $length;
    protected static $width;

    protected static $buff_type;

    protected static $shoot_interval_time_down;

    /**
     * @return mixed
     */
    public function getShootIntervalTimeDown()
    {
        return $this->shoot_interval_time_down??static::$shoot_interval_time_down;
    }

    /**
     * @param mixed $shoot_interval_time_down
     */
    public function setShootIntervalTimeDown($shoot_interval_time_down)
    {
        $this->shoot_interval_time_down = $shoot_interval_time_down;
    }

    public static function getShootIntervalTimeDownStatic(){
        return static::$shoot_interval_time_down;
    }

    public function active()
    {
        parent::active(); // TODO: Change the autogenerated stub
        $this->getTankGot()->shootIntervalDown($this->getShootIntervalTimeDown());
    }
}