<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/3
 * Time: 8:15
 */
class PayMine extends Bullet
{
    protected static $concept;
    protected static $id;
    protected static $die;
    protected static $length;
    protected static $width;

    protected static $hp;
    protected static $life;
    protected static $side;
    protected static $is_no_enemy;

    protected static $face_to;
    protected static $speed;
    protected static $attack;
    protected static $from;
    protected static $number;

    protected static $set_mine_number;

    /**
     * @return mixed
     */
    public static function getSetMineNumberStatic()
    {
        return static::$set_mine_number;
    }

    public function destroy($update = true)
    {
        $this->getFrom()->payMineSet($this->getX(),$this->getY());
        parent::destroy($update); // TODO: Change the autogenerated stub
    }

}